# Generated by Django 6.0.7 on 2026-08-04 02:07

import django.db.models.deletion
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_enum.fields.EnumCharField(choices=[('APPLIED', 'Applied'), ('UNDER_REVIEW', 'UnderReview'), ('SHORTLISTED', 'Shortlisted'), ('IN_PROGRESS', 'InProgress'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], max_length=12)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_enum.fields.EnumCharField(choices=[('INTERNSHIP', 'Internship'), ('COMPLETED', 'Completed'), ('GRADUATED', 'Graduated'), ('DEGREE_IN_PROGRESS', 'DegreeInProgress'), ('INCOMPLETE', 'Incomplete')], max_length=18)),
                ('term_type', django_enum.fields.EnumCharField(choices=[('SEMESTER', 'Semester'), ('FOUR_MONTH_TERM', 'FourMonthTerm'), ('OPEN', 'Open')], max_length=15)),
                ('starting_date', models.DateField()),
                ('finishing_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanySector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('type', django_enum.fields.EnumCharField(choices=[('DOCTORATE', 'Doctorate'), ('MASTER', 'Master'), ('POSTGRADUATE', 'Postgraduate'), ('ENGINEERING', 'Engineering'), ('BACHELOR', 'Bachelor'), ('TECHNICAL', 'Technical')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('address_or_url', models.CharField(max_length=255)),
                ('status', django_enum.fields.EnumCharField(choices=[('SCHEDULED', 'Scheduled'), ('PENDING_CONFIRMATION', 'PendingConfirmation'), ('RESCHEDULED', 'Rescheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'NoShow')], max_length=20)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('salary_period', django_enum.fields.EnumCharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly'), ('PER_PROJECT', 'PerProject')], max_length=11)),
                ('workplace_type', django_enum.fields.EnumCharField(choices=[('ON_SITE', 'OnSite'), ('HYBRID', 'Hybrid'), ('REMOTE', 'Remote')], max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('published_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('type', django_enum.fields.EnumCharField(choices=[('SOFT', 'Soft'), ('HARD', 'Hard'), ('LANGUAGE', 'Language')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('biografy', models.TextField(blank=True, max_length=500, null=True)),
                ('gender', django_enum.fields.EnumCharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NON_BINARY', 'NonBinary')], max_length=10, null=True)),
                ('date_of_birth', models.DateField()),
                ('email_address', models.EmailField(max_length=60, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('biography', models.TextField(blank=True, max_length=500, null=True)),
                ('email_address', models.EmailField(max_length=60, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('establish_year', models.IntegerField(blank=True, null=True)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api_rest.city')),
            ],
        ),
    ]
