# Generated by Django 6.0.6 on 2026-07-17 03:47

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('state', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='CompanySector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('type', django_enum.fields.EnumCharField(choices=[('D', 'DOCTORATE'), ('M', 'MASTER'), ('E', 'ENGINEERING'), ('B', 'BACHELOR'), ('T', 'TECHNICAL')], max_length=1)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('type__in', ['D', 'M', 'E', 'B', 'T'])), name='api_rest_Degree_type_DegreeType')],
            },
        ),
    ]
