# Generated by Django 6.0.7 on 2026-08-03 11:34

import django.db.models.deletion
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanySector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('biography', models.TextField(blank=True, max_length=500, null=True)),
                ('email_address', models.CharField(max_length=60, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('establish_year', models.IntegerField(blank=True, null=True)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.city')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.companysector')),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('type', django_enum.fields.EnumCharField(choices=[('D', 'DOCTORATE'), ('M', 'MASTER'), ('P', 'POSTGRADUATE'), ('E', 'ENGINEERING'), ('B', 'BACHELOR'), ('T', 'TECHNICAL')], max_length=1)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('type__in', ['D', 'M', 'P', 'E', 'B', 'T'])), name='api_rest_Degree_type_DegreeType')],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('min_salary', models.DecimalField(decimal_places=3, max_digits=8)),
                ('max_salary', models.DecimalField(decimal_places=3, max_digits=8)),
                ('salary_period', django_enum.fields.EnumCharField(choices=[('H', 'HOURLY'), ('D', 'DAILY'), ('W', 'WEEKLY'), ('M', 'MONTHLY'), ('Y', 'YEARLY'), ('P', 'PER_PROJECT')], max_length=1)),
                ('workplace_type', django_enum.fields.EnumCharField(choices=[('O', 'ON_SITE'), ('H', 'HYBRID'), ('R', 'REMOTE')], max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('published_on', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.city')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.companyprofile')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.degree')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.jobtype')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('type', django_enum.fields.EnumCharField(choices=[('S', 'SOFT'), ('H', 'HARD'), ('L', 'LANGUAGE')], max_length=1)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('type__in', ['S', 'H', 'L'])), name='api_rest_Skill_type_SkillType')],
            },
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.job')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.skill')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api_rest.state'),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('biografy', models.TextField(blank=True, max_length=500, null=True)),
                ('gender', django_enum.fields.EnumCharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('N', 'NON_BINARY')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('email_address', models.CharField(max_length=60, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.city')),
            ],
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_on', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_enum.fields.EnumCharField(choices=[('A', 'APPLIED'), ('U', 'UNDER_REVIEW'), ('S', 'SHORTLISTED'), ('P', 'IN_PROGRESS'), ('H', 'HIRED'), ('R', 'REJECTED'), ('W', 'WITHDRAWN')], max_length=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.city')),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_enum.fields.EnumCharField(choices=[('I', 'INTERNSHIP'), ('C', 'COMPLETED'), ('G', 'GRADUATED'), ('D', 'DEGREE_IN_PROGRESS'), ('U', 'INCOMPLETE')], max_length=1)),
                ('term_type', django_enum.fields.EnumCharField(choices=[('S', 'SEMESTER'), ('F', 'FOUR_MONTH_TERM'), ('O', 'OPEN')], max_length=1)),
                ('starting_date', models.DateField()),
                ('finishing_date', models.DateField(blank=True, null=True)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.degree')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.studentprofile')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.university')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('address_or_url', models.CharField(max_length=255)),
                ('status', django_enum.fields.EnumCharField(choices=[('S', 'SCHEDULED'), ('P', 'PENDING_CONFIRMATION'), ('R', 'RESCHEDULED'), ('C', 'COMPLETED'), ('X', 'CANCELLED'), ('N', 'NO_SHOW')], max_length=1)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.application')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['S', 'P', 'R', 'C', 'X', 'N'])), name='api_rest_Interview_status_StatusType')],
            },
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('salary_period__in', ['H', 'D', 'W', 'M', 'Y', 'P'])), name='api_rest_Job_salary_period_SalaryPeriodType'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('workplace_type__in', ['O', 'H', 'R'])), name='api_rest_Job_workplace_type_WorkplaceType'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('gender__in', ['M', 'F', 'N'])), name='api_rest_StudentProfile_gender_GenderType'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['A', 'U', 'S', 'P', 'H', 'R', 'W'])), name='api_rest_Application_status_StatusType'),
        ),
        migrations.AddConstraint(
            model_name='career',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['I', 'C', 'G', 'D', 'U'])), name='api_rest_Career_status_StatusType'),
        ),
        migrations.AddConstraint(
            model_name='career',
            constraint=models.CheckConstraint(condition=models.Q(('term_type__in', ['S', 'F', 'O'])), name='api_rest_Career_term_type_TermType'),
        ),
    ]
