# Generated by Django 6.0.6 on 2026-07-18 04:11

import django.db.models.deletion
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('biography', models.TextField(blank=True, max_length=500, null=True)),
                ('email_address', models.CharField(max_length=60, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('establish_year', models.IntegerField(blank=True, null=True)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.city')),
                ('sector_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.companysector')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('type', django_enum.fields.EnumCharField(choices=[('S', 'SOFT'), ('H', 'HARD')], max_length=1)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('type__in', ['S', 'H'])), name='api_rest_Skill_type_SkillType')],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('biografy', models.TextField(blank=True, max_length=500, null=True)),
                ('gender', django_enum.fields.EnumCharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('email_address', models.CharField(max_length=60, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.city')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('gender__in', ['M', 'F'])), name='api_rest_StudentProfile_gender_GenderType')],
            },
        ),
    ]
