# Generated by Django 6.0.7 on 2026-08-04 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_rest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api_rest.companysector'),
        ),
        migrations.AddConstraint(
            model_name='degree',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['DOCTORATE', 'MASTER', 'POSTGRADUATE', 'ENGINEERING', 'BACHELOR', 'TECHNICAL'])), name='api_rest_Degree_type_DegreeType'),
        ),
        migrations.AddField(
            model_name='career',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.degree'),
        ),
        migrations.AddField(
            model_name='interview',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.application'),
        ),
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.city'),
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.companyprofile'),
        ),
        migrations.AddField(
            model_name='job',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.degree'),
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.job'),
        ),
        migrations.AddField(
            model_name='jobskill',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.job'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.jobtype'),
        ),
        migrations.AddField(
            model_name='savedjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.job'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['SOFT', 'HARD', 'LANGUAGE'])), name='api_rest_Skill_type_SkillType'),
        ),
        migrations.AddField(
            model_name='jobskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.skill'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api_rest.state'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api_rest.city'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedjob',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.studentprofile'),
        ),
        migrations.AddField(
            model_name='career',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.studentprofile'),
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.studentprofile'),
        ),
        migrations.AddField(
            model_name='studentskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.skill'),
        ),
        migrations.AddField(
            model_name='studentskill',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.studentprofile'),
        ),
        migrations.AddField(
            model_name='university',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.city'),
        ),
        migrations.AddField(
            model_name='career',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.university'),
        ),
        migrations.AddConstraint(
            model_name='interview',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['SCHEDULED', 'PENDING_CONFIRMATION', 'RESCHEDULED', 'COMPLETED', 'CANCELLED', 'NO_SHOW'])), name='api_rest_Interview_status_StatusType'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('salary_period__in', ['HOURLY', 'DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', 'PER_PROJECT'])), name='api_rest_Job_salary_period_SalaryPeriodType'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('workplace_type__in', ['ON_SITE', 'HYBRID', 'REMOTE'])), name='api_rest_Job_workplace_type_WorkplaceType'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('gender__in', ['MALE', 'FEMALE', 'NON_BINARY']), ('gender__isnull', True), _connector='OR'), name='api_rest_StudentProfile_gender_GenderType'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['APPLIED', 'UNDER_REVIEW', 'SHORTLISTED', 'IN_PROGRESS', 'HIRED', 'REJECTED', 'WITHDRAWN'])), name='api_rest_Application_status_StatusType'),
        ),
        migrations.AddConstraint(
            model_name='career',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['INTERNSHIP', 'COMPLETED', 'GRADUATED', 'DEGREE_IN_PROGRESS', 'INCOMPLETE'])), name='api_rest_Career_status_StatusType'),
        ),
        migrations.AddConstraint(
            model_name='career',
            constraint=models.CheckConstraint(condition=models.Q(('term_type__in', ['SEMESTER', 'FOUR_MONTH_TERM', 'OPEN'])), name='api_rest_Career_term_type_TermType'),
        ),
    ]
