# Generated by Django 6.0.7 on 2026-08-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='type',
            new_name='job_type',
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='email_address',
            field=models.EmailField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='max_salary',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='job',
            name='min_salary',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='email_address',
            field=models.EmailField(max_length=60, unique=True),
        ),
    ]
