# Generated by Django 6.0.6 on 2026-07-18 04:46

import django.db.models.deletion
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_companyprofile_skill_studentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('min_salary', models.DecimalField(decimal_places=3, max_digits=8)),
                ('max_salary', models.DecimalField(decimal_places=3, max_digits=8)),
                ('salary_period', django_enum.fields.EnumCharField(choices=[('D', 'DAILY'), ('W', 'WEEKLY'), ('M', 'MONTHLY'), ('Y', 'YEARLY'), ('P', 'PER_PROJECT')], max_length=1)),
                ('workplace_type', django_enum.fields.EnumCharField(choices=[('O', 'ON_SITE'), ('H', 'HYBRID'), ('R', 'REMOTE')], max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('published_on', models.DateTimeField(auto_now_add=True)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.city')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.companyprofile')),
                ('degree_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.degree')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.jobtype')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_enum.fields.EnumCharField(choices=[('A', 'APPLIED'), ('U', 'UNDER_REVIEW'), ('S', 'SHORTLISTED'), ('P', 'IN_PROGRESS'), ('H', 'HIRED'), ('R', 'REJECTED'), ('W', 'WITHDRAWN')], max_length=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.studentprofile')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.job')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.city')),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_enum.fields.EnumCharField(choices=[('I', 'INTERNSHIP'), ('C', 'COMPLETED'), ('G', 'GRADUATED'), ('D', 'DEGREE_IN_PROGRESS'), ('U', 'INCOMPLETE')], max_length=1)),
                ('term_type', django_enum.fields.EnumCharField(choices=[('S', 'SEMESTER'), ('F', 'FOUR_MONTH_TERM'), ('O', 'OPEN')], max_length=1)),
                ('starting_date', models.DateField()),
                ('finishing_date', models.DateField(blank=True, null=True)),
                ('degree_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.degree')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.studentprofile')),
                ('university_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.university')),
            ],
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('salary_period__in', ['D', 'W', 'M', 'Y', 'P'])), name='api_rest_Job_salary_period_SalaryPeriodType'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('workplace_type__in', ['O', 'H', 'R'])), name='api_rest_Job_workplace_type_WorkplaceType'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['A', 'U', 'S', 'P', 'H', 'R', 'W'])), name='api_rest_Application_status_StatusType'),
        ),
        migrations.AddConstraint(
            model_name='career',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['I', 'C', 'G', 'D', 'U'])), name='api_rest_Career_status_StatusType'),
        ),
        migrations.AddConstraint(
            model_name='career',
            constraint=models.CheckConstraint(condition=models.Q(('term_type__in', ['S', 'F', 'O'])), name='api_rest_Career_term_type_TermType'),
        ),
    ]
