# Generated by Django 6.0.7 on 2026-08-11 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api_rest.job'),
        ),
        migrations.AlterField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api_rest.studentprofile'),
        ),
        migrations.AlterField(
            model_name='career',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='api_rest.degree'),
        ),
        migrations.AlterField(
            model_name='career',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='api_rest.studentprofile'),
        ),
        migrations.AlterField(
            model_name='career',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='api_rest.university'),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cities', to='api_rest.state'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='company_profiles', to='api_rest.city'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='company_profiles', to='api_rest.companysector'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='api_rest.application'),
        ),
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api_rest.city'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api_rest.companyprofile'),
        ),
        migrations.AlterField(
            model_name='job',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api_rest.degree'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api_rest.jobtype'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='student_profiles', to='api_rest.city'),
        ),
        migrations.AlterField(
            model_name='university',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='api_rest.city'),
        ),
    ]
