# Generated by Django 6.0.6 on 2026-07-18 04:55

import django.db.models.deletion
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_job_application_university_career_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.job')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.skill')),
            ],
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_on', models.DateTimeField(auto_now_add=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.job')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.skill')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('address_or_url', models.CharField(max_length=255)),
                ('status', django_enum.fields.EnumCharField(choices=[('S', 'SCHEDULED'), ('P', 'PENDING_CONFIRMATION'), ('R', 'RESCHEDULED'), ('C', 'COMPLETED'), ('X', 'CANCELLED'), ('N', 'NO_SHOW')], max_length=1)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.application')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['S', 'P', 'R', 'C', 'X', 'N'])), name='api_rest_Interview_status_StatusType')],
            },
        ),
    ]
