# Generated by Django 6.0.6 on 2026-07-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0004_jobskill_savedjob_studentskill_interview'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='application',
            name='api_rest_Application_status_StatusType',
        ),
        migrations.RemoveConstraint(
            model_name='career',
            name='api_rest_Career_status_StatusType',
        ),
        migrations.RemoveConstraint(
            model_name='career',
            name='api_rest_Career_term_type_TermType',
        ),
        migrations.RemoveConstraint(
            model_name='degree',
            name='api_rest_Degree_type_DegreeType',
        ),
        migrations.RemoveConstraint(
            model_name='interview',
            name='api_rest_Interview_status_StatusType',
        ),
        migrations.RemoveConstraint(
            model_name='job',
            name='api_rest_Job_salary_period_SalaryPeriodType',
        ),
        migrations.RemoveConstraint(
            model_name='job',
            name='api_rest_Job_workplace_type_WorkplaceType',
        ),
        migrations.RemoveConstraint(
            model_name='skill',
            name='api_rest_Skill_type_SkillType',
        ),
        migrations.RemoveConstraint(
            model_name='studentprofile',
            name='api_rest_StudentProfile_gender_GenderType',
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('A', 'APPLIED'), ('U', 'UNDER_REVIEW'), ('S', 'SHORTLISTED'), ('P', 'IN_PROGRESS'), ('H', 'HIRED'), ('R', 'REJECTED'), ('W', 'WITHDRAWN')], max_length=1),
        ),
        migrations.AlterField(
            model_name='career',
            name='status',
            field=models.CharField(choices=[('I', 'INTERNSHIP'), ('C', 'COMPLETED'), ('G', 'GRADUATED'), ('D', 'DEGREE_IN_PROGRESS'), ('U', 'INCOMPLETE')], max_length=1),
        ),
        migrations.AlterField(
            model_name='career',
            name='term_type',
            field=models.CharField(choices=[('S', 'SEMESTER'), ('F', 'FOUR_MONTH_TERM'), ('O', 'OPEN')], max_length=1),
        ),
        migrations.AlterField(
            model_name='degree',
            name='type',
            field=models.CharField(choices=[('D', 'DOCTORATE'), ('M', 'MASTER'), ('E', 'ENGINEERING'), ('B', 'BACHELOR'), ('T', 'TECHNICAL')], max_length=1),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('S', 'SCHEDULED'), ('P', 'PENDING_CONFIRMATION'), ('R', 'RESCHEDULED'), ('C', 'COMPLETED'), ('X', 'CANCELLED'), ('N', 'NO_SHOW')], max_length=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_period',
            field=models.CharField(choices=[('H', 'HOURLY'), ('D', 'DAILY'), ('W', 'WEEKLY'), ('M', 'MONTHLY'), ('Y', 'YEARLY'), ('P', 'PER_PROJECT')], max_length=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='workplace_type',
            field=models.CharField(choices=[('O', 'ON_SITE'), ('H', 'HYBRID'), ('R', 'REMOTE')], max_length=1),
        ),
        migrations.AlterField(
            model_name='skill',
            name='type',
            field=models.CharField(choices=[('S', 'SOFT'), ('H', 'HARD')], max_length=1),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('N', 'NON_BINARY')], max_length=1),
        ),
    ]
