# Generated by Django 6.0.7 on 2026-08-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0004_alter_application_job_alter_application_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(related_name='jobs', through='api_rest.JobSkill', to='api_rest.skill'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='skills',
            field=models.ManyToManyField(related_name='students', through='api_rest.StudentSkill', to='api_rest.skill'),
        ),
    ]
