# Generated by Django 6.0.6 on 2026-08-01 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0005_remove_application_api_rest_application_status_statustype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
        migrations.AlterField(
            model_name='degree',
            name='type',
            field=models.CharField(choices=[('D', 'DOCTORATE'), ('M', 'MASTER'), ('P', 'POSTGRADUATE'), ('E', 'ENGINEERING'), ('B', 'BACHELOR'), ('T', 'TECHNICAL')], max_length=1),
        ),
        migrations.AlterField(
            model_name='skill',
            name='type',
            field=models.CharField(choices=[('S', 'SOFT'), ('H', 'HARD'), ('L', 'LANGUAGE')], max_length=1),
        ),
        migrations.AddField(
            model_name='city',
            name='state_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='api_rest.state'),
        ),
    ]
