# Generated by Django 6.0.6 on 2026-08-01 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0006_state_remove_city_state_alter_degree_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api_rest.state'),
        ),
    ]
