# Generated by Django 6.0.6 on 2026-08-02 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0007_alter_city_state_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='job_id',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='career',
            old_name='degree_id',
            new_name='degree',
        ),
        migrations.RenameField(
            model_name='career',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='career',
            old_name='university_id',
            new_name='university',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='state_id',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='sector_id',
            new_name='sector',
        ),
        migrations.RenameField(
            model_name='interview',
            old_name='application_id',
            new_name='application',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='degree_id',
            new_name='degree',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='type_id',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='jobskill',
            old_name='job_id',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='jobskill',
            old_name='skill_id',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='savedjob',
            old_name='job_id',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='savedjob',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='studentskill',
            old_name='skill_id',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='studentskill',
            old_name='student_id',
            new_name='student',
        ),
    ]
