# Generated by Django 6.0.6 on 2026-08-02 22:29

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0008_rename_job_id_application_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=django_enum.fields.EnumCharField(choices=[('A', 'APPLIED'), ('U', 'UNDER_REVIEW'), ('S', 'SHORTLISTED'), ('P', 'IN_PROGRESS'), ('H', 'HIRED'), ('R', 'REJECTED'), ('W', 'WITHDRAWN')], max_length=1),
        ),
        migrations.AlterField(
            model_name='career',
            name='status',
            field=django_enum.fields.EnumCharField(choices=[('I', 'INTERNSHIP'), ('C', 'COMPLETED'), ('G', 'GRADUATED'), ('D', 'DEGREE_IN_PROGRESS'), ('U', 'INCOMPLETE')], max_length=1),
        ),
        migrations.AlterField(
            model_name='career',
            name='term_type',
            field=django_enum.fields.EnumCharField(choices=[('S', 'SEMESTER'), ('F', 'FOUR_MONTH_TERM'), ('O', 'OPEN')], max_length=1),
        ),
        migrations.AlterField(
            model_name='degree',
            name='type',
            field=django_enum.fields.EnumCharField(choices=[('D', 'DOCTORATE'), ('M', 'MASTER'), ('P', 'POSTGRADUATE'), ('E', 'ENGINEERING'), ('B', 'BACHELOR'), ('T', 'TECHNICAL')], max_length=1),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=django_enum.fields.EnumCharField(choices=[('S', 'SCHEDULED'), ('P', 'PENDING_CONFIRMATION'), ('R', 'RESCHEDULED'), ('C', 'COMPLETED'), ('X', 'CANCELLED'), ('N', 'NO_SHOW')], max_length=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_period',
            field=django_enum.fields.EnumCharField(choices=[('H', 'HOURLY'), ('D', 'DAILY'), ('W', 'WEEKLY'), ('M', 'MONTHLY'), ('Y', 'YEARLY'), ('P', 'PER_PROJECT')], max_length=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='workplace_type',
            field=django_enum.fields.EnumCharField(choices=[('O', 'ON_SITE'), ('H', 'HYBRID'), ('R', 'REMOTE')], max_length=1),
        ),
        migrations.AlterField(
            model_name='skill',
            name='type',
            field=django_enum.fields.EnumCharField(choices=[('S', 'SOFT'), ('H', 'HARD'), ('L', 'LANGUAGE')], max_length=1),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=django_enum.fields.EnumCharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('N', 'NON_BINARY')], max_length=1),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['A', 'U', 'S', 'P', 'H', 'R', 'W'])), name='api_rest_Application_status_StatusType'),
        ),
        migrations.AddConstraint(
            model_name='career',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['I', 'C', 'G', 'D', 'U'])), name='api_rest_Career_status_StatusType'),
        ),
        migrations.AddConstraint(
            model_name='career',
            constraint=models.CheckConstraint(condition=models.Q(('term_type__in', ['S', 'F', 'O'])), name='api_rest_Career_term_type_TermType'),
        ),
        migrations.AddConstraint(
            model_name='degree',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['D', 'M', 'P', 'E', 'B', 'T'])), name='api_rest_Degree_type_DegreeType'),
        ),
        migrations.AddConstraint(
            model_name='interview',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['S', 'P', 'R', 'C', 'X', 'N'])), name='api_rest_Interview_status_StatusType'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('salary_period__in', ['H', 'D', 'W', 'M', 'Y', 'P'])), name='api_rest_Job_salary_period_SalaryPeriodType'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('workplace_type__in', ['O', 'H', 'R'])), name='api_rest_Job_workplace_type_WorkplaceType'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['S', 'H', 'L'])), name='api_rest_Skill_type_SkillType'),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('gender__in', ['M', 'F', 'N'])), name='api_rest_StudentProfile_gender_GenderType'),
        ),
    ]
