# Generated by Django 6.0.7 on 2026-08-03 12:07

import users.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='eduworkuser',
            managers=[
                ('objects', users.managers.EduWorkUserManager()),
            ],
        ),
    ]
